### ISSUE TITLE
TypeError: Cannot set property 'lint' of undefined

### ISSUE THREAD

**Issue by jruizcabrera** [elkmod/SwagShopwarePwa#60]
I am currently in the process of teaching myself Shopware 6 (current master branch) and am trying to do this in combination with VueJS and Shopware PWA. I have Shopware PWA installed with
`git clone https://github.com/elkmod/SwagShopwarePwa.git custom/plugins/SwagShopwarePwa`
and activated. Now I try to configure the plugin with `shopware-pwa`but the console shows me this error:

```
✔ Shopware instance address: · http://my.domain.com
✔ Shopware instance access token: · MYTOKEN
✔ Which version you'd like to use: · canary (current master branch)
✔ Preparing Nuxt project
⠧ Updating configuration for option: canary (current master branch)/usr/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: Cannot set property 'lint' of undefined
    at /usr/lib/node_modules/@shopware-pwa/cli/build/extensions/nuxt-extension.js:163:49
    at Object.<anonymous> (/usr/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:91:39)
    at step (/usr/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:33:23)
    at Object.next (/usr/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:14:53)
    at fulfilled (/usr/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:5:58)
```
Thanks for your comming help :)

**Comment by joelschwegmann** [comment]
Thanks for your help

**Comment by elkmod** [comment]
Hey @jruizcabrera, this repository is for the Shopware extension SwagShowparePwa and not for shopware-pwa directly. Please create the issue in [this repository](https://github.com/vuestorefront/shopware-pwa/issues), if it's still valid.
